secondflutter
AiNarikoSachi/MDP pull request #4
Opened 2021-12-22 10:02 UTC by AiNarikoSachi

2021-12-23 04:17 UTC, Sveta-K13 requested changes
Все ок, но надо поправить момент с MaterialApp - это грубая ошибка, хоть пока и не стрельнула.
@AiNarikoSachi поправь плз

2021-12-23 04:17 UTC, Sveta-K13 commented on FlutterFirstProject/lib/marvel_info.dart
> +    return MaterialApp(
не надо каждый экран заворачивать в виджет MaterialApp - он создает навигатор, инициализирует систему фокусов, переопределяет тему и др. Он нужен только в корне приложения. Если нужно для экрана переопределить тему, то используй спец виджет Theme.
Btw: навигатор работает как ожидается только потому что ты определяешь его в этом же виджете и контекст указывает на элемент, внутри которого MaterialApp

2021-12-23 14:09 UTC, AiNarikoSachi commented
@Sveta-K13 Убрал MaterialApp

2021-12-24 05:12 UTC, Sveta-K13 commented
👍 Лабораторная 2 зачтена :heavy_check_mark:

2021-12-24 09:48 UTC, merged