thirdflutter
AiNarikoSachi/MDP pull request #5
Opened 2021-12-24 10:50 UTC by AiNarikoSachi

2021-12-24 14:12 UTC, Sveta-K13 requested changes
@AiNarikoSachi для сдачи надо как минимум исправить запрос списка

2021-12-24 14:12 UTC, Sveta-K13 commented on FlutterFirstProject/lib/main.dart
> +    if (isLoaded == true && heroes.isEmpty) {
кнб: можно было просто написать (isLoaded && heroes.isEmpty)

2021-12-24 14:12 UTC, Sveta-K13 commented on FlutterFirstProject/lib/main.dart
> +          home: Scaffold(
кнб: ты по сути работает внутри этой страницы, ее бы вынести в отдельный класс и там определять что в body рисовать, а не весь апп переопределять

2021-12-24 14:12 UTC, Sveta-K13 commented on FlutterFirstProject/lib/main.dart
> +            body: Column(
кнб: и можно было конечно на время загрузки лоадер бахнуть)

2021-12-24 14:12 UTC, Sveta-K13 commented on FlutterFirstProject/lib/marvel_api.dart
> +    try {
не соответствует пункту [приемки](https://github.com/effectiveband/fkn_labs/blob/master/Flutter/Lab03.md#%D0%BA%D1%80%D0%B8%D1%82%D0%B5%D1%80%D0%B8%D0%B8-%D0%BF%D1%80%D0%B8%D0%B5%D0%BC%D0%BA%D0%B8)
`Для получения списка герое используется GET запрос /public/characters из Marvel Api`

2021-12-26 13:47 UTC, AiNarikoSachi commented
@Sveta-K13 исправил ошибки

2021-12-27 06:58 UTC, Sveta-K13 approved these changes
Лабораторная 3 зачтена ✔️

2021-12-27 06:58 UTC, Sveta-K13 commented on FlutterFirstProject/lib/main.dart
> +                          builder: (BuildContext context) => MarvelInfo(
кнб: по-хорошему для страницы MarvelInfo надо также сделать получение подробной инфы из апи (с состоянием загрузки и ошибки), но ладно, в рамках заданной функциональности пойдет 👌

2021-12-27 07:49 UTC, merged